language: shell

os: windows

env:
  - BUILD_TYPE=Debug VCVARS=vcvarsamd64_arm TESTING=OFF
  - BUILD_TYPE=Release VCVARS=vcvarsamd64_arm TESTING=OFF
  - BUILD_TYPE=MinSizeRel VCVARS=vcvarsamd64_arm TESTING=OFF

  - BUILD_TYPE=Debug VCVARS=vcvarsamd64_arm64 TESTING=OFF
  - BUILD_TYPE=Release VCVARS=vcvarsamd64_arm64 TESTING=OFF
  - BUILD_TYPE=MinSizeRel VCVARS=vcvarsamd64_arm64 TESTING=OFF

  - BUILD_TYPE=Debug VCVARS=vcvars32 TESTING=OFF
  - BUILD_TYPE=Release VCVARS=vcvars32 TESTING=OFF
  - BUILD_TYPE=MinSizeRel VCVARS=vcvars32 TESTING=OFF

  - BUILD_TYPE=Debug VCVARS=vcvars64 TESTING=OFF
  - BUILD_TYPE=Release VCVARS=vcvars64 TESTING=OFF
  - BUILD_TYPE=MinSizeRel VCVARS=vcvars64 TESTING=OFF

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR} && pwd
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.11/cmake-3.11.0-win64-x64.zip
  - echo "615dfb0813443c1ff56ae0e9d6dbfc61 *cmake-3.11.0-win64-x64.zip" > cmake_md5.txt
  - md5sum -c cmake_md5.txt
  - 7z x -y cmake-3.11.0-win64-x64.zip
  - PATH=${DEPS_DIR}/cmake-3.11.0-win64-x64:${DEPS_DIR}/cmake-3.11.0-win64-x64/bin:$PATH

before_script:

  # document the version
  - cmake --version

  # set enviromental variables
  - ls /c

  - ls "/c/Progra~2/Microsoft Visual Studio 14.0"
  - ls "/c/Progra~2/Microsoft Visual Studio/2017"

  - tree "/c/Progra~2/Microsoft Visual Studio 14.0"
  - tree "/c/Progra~2/Microsoft Visual Studio/2017"

  #- "/c/Progra~2/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/${VCVARS}.bat"

  # generate the build files
  - cd ${TRAVIS_BUILD_DIR} && mkdir build && cd build
  - cmake -G"NMake Makefiles" -DCMAKE_VERBOSE_MAKEFILE=FALSE -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
          -DBUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
          -DDIST_ROOT="${TRAVIS_BUILD_DIR}/build/dist"
          -DENABLE_TESTS=${TESTING}
          ..
script:
  - cmake --build . --config ${BUILD_TYPE} --target install

addons:
  coverity_scan:
    project:
      name: “jwinarske/pthreads4w"
    notification_email: joel.winarske@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake -DCMAKE_VERBOSE_MAKEFILE=TRUE -DDCMAKE_INSTALL_PREFIX=`pwd`/dist .."
    build_command:   "cmake --build . --target install"
    branch_pattern: coverity_scan
