function(get_target_arch out)
    if (CMAKE_SYSTEM_PROCESSOR MATCHES \"^(arm|ARM)\")
        set(\${out} \"ARM\" PARENT_SCOPE)
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES \"^(aarch64|AARCH64|arm64|ARM64)\")
        set(\${out} \"ARM64\" PARENT_SCOPE)
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES \"^(x86_64|X86_64|amd64|AMD64)\")
        set(\${out} \"x86_64\" PARENT_SCOPE)
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES \"^(x86|X86|i386|I386|i686|I686)\")
        set(\${out} \"x86\" PARENT_SCOPE)
    else()
        set(\${out} \"unknown\" PARENT_SCOPE)
    endif()
endfunction()
